import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../../presentation/providers/settings_provider.dart';

class RuntimeLocalizations {
  // Minimal runtime translations for strings not present in ARB.
  static final Map<String, Map<String, String>> _t = {
    'it': {
      // --- Routing ---
      'routing_details': 'Dettagli Percorso',
      'routing_solutions': 'soluzioni',
      'routing_tab_overview': 'Panoramica',
      'routing_tab_segments': 'Tratte',
      'routing_tab_stops': 'Fermate',
      'routing_trains_used': 'Treni utilizzati',
      'routing_summary': 'Riepilogo percorso',
      'routing_direct': 'DIRETTO',
      'routing_changes': 'CON CAMBIO ({count})',
      'routing_duration': 'Durata: {duration}',
      'routing_origin_hint': 'Da dove parti? (es. Roma)',
      'routing_destination_hint': 'Dove vai? (es. Milano)',
      'routing_search_btn': 'Cerca Soluzioni',
      'routing_empty': 'Inserisci la stazione di partenza e di destinazione per trovare i percorsi migliori.',
      'routing_no_results': 'Nessuna soluzione trovata tra queste stazioni.',
      'routing_time_now': 'Ora',
      'routing_time_label': 'Orario',
      'routing_time_date_label': 'Data',
      
      // --- Existing keys ---
      'trip_stops_title': 'Fermate del Viaggio',
      'no_updates': 'Nessun aggiornamento',
      'trip_stops_unavailable': 'Dettagli fermate non disponibili per {provider}',
      'live': 'LIVE',
      'details_and_position': 'Dettagli e Posizione',
      'press_for_info': 'Premi per info',
      'destination_na': 'Destinazione N/A',
      'filter_all': 'Tutti',
      'filter_stops': 'Fermate',
      'filter_trains': 'Treni',
      'filter_buses': 'Bus',
      'favorites': 'Preferiti',
      'automatic': 'Automatico',
      'device_language': 'Lingua del dispositivo',
      'settings_header_title': 'Impostazioni',
      'settings_header_subtitle': 'Personalizza lingua, tema e aggiornamenti in pochi tocchi.',
      'settings_language': 'Lingua',
      'settings_theme': 'Tema',
      'settings_auto_refresh': 'Aggiornamento automatico',
      'settings_configuration': 'Configurazione',
      'settings_notifications': 'Notifiche',
      'settings_ui': 'Esperienza UI',
      'settings_map': 'Mappa',
      'settings_map_style': 'Stile mappa',
      'settings_offline_sync': 'Sincronizzazione offline',
      'settings_disclaimer': 'Informazioni e disclaimer',
      'importantInfo': 'Informazioni Importanti',
      'map': 'Mappa',
      'update': 'Aggiorna',
      'offline': 'Offline',
      'save_offline': 'Salva offline',
      'offline_mode': 'Offline',
      'train_saved_offline': 'Treno salvato per modalità offline',
      'train_saved_manual_offline': 'Treno salvato manualmente (auto-sync offline disattivata)',
      'alerts': 'Avvisi',
      'theme_light': 'Chiaro',
      'theme_dark': 'Scuro',
      'theme_system': 'Sistema',
      'auto': 'Auto',
      'off': 'Spento',
      'managed_by_server': 'Gestito dal server in base al traffico',
      'map_style_dark': 'Scuro',
      'map_style_light': 'Chiaro',
      'map_style_streets': 'Strade',
      'map_style_satellite': 'Satellite',
      'map_style_satellite_streets': 'Sat+Str',
      'other': 'Altro',
      'custom_style_url': 'URL stile personalizzato',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test Notifiche',
      'train_notifications_config': 'Configura notifiche treni',
      'bus_notifications_config': 'Configura notifiche autobus',
      'station_id': 'Station ID',
      'provider': 'Provider',
      'base_url_optional': 'Base URL (opzionale)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Preavviso arrivo stazione',
      'train_arrival_pre_notice_desc': 'Ricevi un avviso N minuti prima dell\'arrivo stimato alla tua fermata (5–20 minuti).',
      'vector_train_logos': 'Loghi Treni Vettoriali',
      'vector_train_logos_desc': 'Scarica e visualizza loghi ufficiali per le categorie dei treni (es. Frecciarossa, Intercity) invece del testo semplice.',
      'update_configuration': 'Aggiorna Configurazione',
      'update_provider_configuration': 'Aggiorna configurazione provider',
      'configuration_update_desc': 'Scarica l\'ultima configurazione dei provider di autobus dal server',
      'configuration_updated_success': 'Configurazione aggiornata con successo',
      'offline_sync_title': 'Sincronizzazione Offline',
      'offline_sync_desc': 'Scarica automaticamente i dati di percorsi e orari quando sincronizzi da una città. I dati verranno salvati localmente e disponibili anche senza connessione.',
      'disclaimer_title': 'BC Transporter Non Sostituisce i Canali Ufficiali',
      'disclaimer_text': 'Questa applicazione non intende in alcun modo sostituire le piattaforme ufficiali delle compagnie ferroviarie o i loro canali di vendita. BC Transporter fornisce informazioni e dati di tracciamento a scopo puramente informativo.\n\nPer l\'acquisto dei biglietti e per verificare disponibilità, tariffe, condizioni di viaggio e conferme ufficiali, è necessario rivolgersi esclusivamente ai canali ufficiali delle compagnie ferroviarie (siti web, app ufficiali, agenzie autorizzate o rivenditori certificati).\n\nI biglietti devono essere acquistati tramite le piattaforme ufficiali; BC Transporter non vende biglietti e non sostituisce i canali ufficiali di vendita.\n\nNon ci assumiamo responsabilità per acquisti effettuati su canali non ufficiali o per informazioni di prezzo/condizioni non aggiornate. Eventuali link a siti di terze parti sono forniti a scopo di comodità e non implicano approvazione o partnership.',
      'language_italian': 'Italiano',
      'language_english': 'English',
      'language_german': 'Deutsch',
      'explore': 'Esplora',
      'greeting': 'Ciao, {name} 👋',
      'ready_to_go': 'Pronto a partire?',
      'refresh_realtime_tooltip': 'Aggiorna dati real-time',
      'train_removed_favorites': 'Treno rimosso dai preferiti',
      'error_removing_favorite': 'Errore durante la rimozione del preferito',
      'undo': 'Annulla',
      'train_added_favorites': 'Treno aggiunto ai preferiti',
      'error_adding_favorite': "Errore durante l'aggiunta",
      'no_route_for_line': 'Nessun percorso disponibile per la linea {line}',
      'upcoming_departures': 'Prossime Partenze',
      'remove_from_favorites': 'Rimuovi dai preferiti',
      'add_to_favorites': 'Aggiungi ai preferiti',
      'guest': 'Ospite',
      'where_to_go_today': 'Dove vuoi andare oggi?',
      'explore_map': 'Esplora la Mappa',
      'explore_map_desc': 'Visualizza bus e treni in tempo reale sulla mappa interattiva.',
      'service_status': 'Stato del Servizio',
      'status_regular': 'Regolare',
      'status_delays': 'Ritardi',
      'your_favorites': 'I tuoi Preferiti',
      'see_all': 'Vedi tutti',
      'no_favorites_saved': 'Nessun preferito salvato',
      'greeting_morning': 'Buongiorno',
      'greeting_afternoon': 'Buon pomeriggio',
      'greeting_evening': 'Buonasera',
      'quick_actions_title': 'Azioni rapide',
      'action_map': 'Mappa',
      'action_ticket': 'Ticket',
      'action_routes': 'Percorsi',
      'action_alerts': 'Avvisi',
      'planes_label': 'Aerei',
      'today_badge': 'OGGI',
      'change_btn': 'Cambia',
      'weather_unavailable': 'Meteo non disponibile',
      'bus_stop_label': 'Fermata Bus',
      'station_label': 'Stazione',
      'local_label': 'Locale',
      'your_position': 'La tua posizione',
      'select_city': 'Seleziona città',
      'search_city_weather': 'Cerca la tua città per il meteo',
      'city_search_hint': 'es. Milano, Parigi, London…',
      'use_my_position': 'Usa la mia posizione',
      'detecting_gps': 'Rilevamento in corso…',
      'auto_detect_gps': 'Rileva automaticamente via GPS',
      'search_results_label': 'Risultati ricerca',
      'no_city_found': 'Nessuna città trovata',
      'type_city_name': 'Inizia a digitare il nome\ndella città',
      'permission_denied_location': 'Permesso posizione negato. Abilitalo nelle impostazioni.',
      'gps_unavailable': 'Impossibile rilevare la posizione GPS',
      'logo_source': 'Fonte Loghi',
      'logos_official': 'Ufficiali',
      'logos_custom': 'Custom',
      'share_trip': 'Condividi',
      'share_trip_msg': 'Segui il mio viaggio live',
      'share_failed': 'Condivisione non riuscita, riprova',
      'shared_trip': 'Viaggio condiviso',
      'trip_not_found': 'Viaggio non trovato',
      'trip_expired': 'Questo link è scaduto',
      'trip_load_error': 'Errore di rete, riprova',
      'estimated_label': 'Stimato',
      'stops_title': 'Fermate',
      'delay_minutes': 'Ritardo: {minutes} min',
      'early_minutes': 'Anticipo: {minutes} min',
      'on_time': 'In orario',
      'remaining_stops': 'Fermate rimanenti: {count}',
      'notify_until': 'Notifica fino a...',
      'choose_stop_from_list': 'Scegli una fermata dalla lista',
      'stops_list_unavailable_general_notification': 'Lista fermate non disponibile, verrà usata notifica generale.',
      'notification_preview': 'Anteprima notifica',
      'notify_to_selected_stop': 'Notifica fino alla fermata selezionata',
      'notify_general': 'Notifica generale',
      'arrivals': 'Arrivi',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Ritardo',
      'origin': 'Origine',
      'destination': 'Destinazione',
      'est_prefix': 'Est: {time}',
      'in_transit': 'In viaggio',
      'on_time_small': 'In orario',
      'loading': 'Caricamento...',
      'delay_short': '+{minutes}min',
      'notifications': 'Notifiche',
      'notifications_disabled': 'Notifiche disattivate',
      'notification_set': 'Notifica impostata',
      'endpoint_check_failed_country': 'Impossibile verificare l\'endpoint dal country selezionata',
      'endpoint_request_failed': 'Richiesta all\'endpoint {candidate} fallita: HTTP {code}',
      'network_error_endpoint_check': 'Errore di rete durante la verifica dell\'endpoint',
      'cannot_determine_url_set_country': 'Non è possibile determinare l\'URL esatto: imposta la country del pannello o utilizza l\'endpoint manuale',
      'disable_notifications_for_this_train': 'Disattiva notifiche per questo treno',
      'retry': 'Riprova',
      'messages': 'Messaggi',
      'close': 'Chiudi',
      'cancelled': 'Annullata',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'BIN',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Accedi per vedere i preferiti',
      'login': 'Accedi',
      'register': 'Registrati',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'Nessuna fermata monitorata',
      'vehicle_info': 'Info Veicolo',
      'vehicle_id': 'ID Veicolo',
      'line': 'Linea',
      'destination_label': 'Destinazione',
      'speed_label': 'Velocità',
      'heading_label': 'Direzione',
      'operator_label': 'Operatore',
      'trip_id_label': 'ID Viaggio',
      'refresh_label': 'Aggiorna',
      'cancel_notification_label': 'Cancella notifica',
      'remove_label': 'Rimuovi',
      'no_monitored_stations': 'Nessuna stazione monitorata',
      'no_monitored_trains': 'Nessun treno monitorato',
      'url_label': 'URL',
      'country_label': 'Country',
      'force_refresh': 'Aggiornamento forzato',
      'notification_cancelled': 'Notifica cancellata',
      'updated_at': 'Aggiornato: {time}',
      'select_item': 'Seleziona {label}',
      'stop_of': 'Fermata di {provider}',
      'saved': 'Salvato',
      'favorite_action': 'Preferito',
      'train_not_found': 'Treno {number} non trovato',
      'train_label': 'Treno {number}',
      'na': 'N/D',
      'unknown': 'Sconosciuta',
      'stop_not_found': 'Fermata "{name}" non trovata',
      'messages_count': 'Messaggi: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Ops! Qualcosa è andato storto',
      'arrival': 'Arrivo',
      'departure': 'Partenza',
      'no_bus_scheduled': 'Nessun bus previsto',
      'scheduled_label': 'Previsto',
      'stats_station_title': 'Statistiche Stazione',
      'stats_day': 'Giorno',
      'stats_week': 'Settim.',
      'stats_month': 'Mese',
      'stats_year': 'Anno',
      'stats_date_of': 'Dati del: {date}',
      'stats_punctuality': 'Puntualità',
      'stats_avg_delay': 'Ritardo Medio',
      'stats_total_trains': 'Treni Totali',
      'stats_cancelled_trains': 'Treni Cancellati',
      'stats_movements_analysis': 'Analisi Movimenti',
      'stats_arrivals': 'Arrivi',
      'stats_departures': 'Partenze',
      'stats_avg_delay_short': 'Ritardo med.',
      'stats_punctuality_short': 'Puntualità',
      'stats_hourly_trend': 'Andamento Orario Ritardi',
      'stats_historical_trend': 'Andamento Storico Ritardi',
      'stats_category_perf': 'Performance per Categoria',
      'stats_worst_trains': 'Treni con Maggior Ritardo',
      'stats_worst_routes': 'Tratte con Maggior Ritardo',
      'stats_no_data': 'Nessun dato disponibile',
      'stats_no_chart_data': 'Nessun dato per il grafico',
      'stats_avg_delay_val': 'Ritardo medio: {val}m',
      'stats_punctuality_val': '{val}% puntualità',
      'stats_unknown_train': 'Treno Sconosciuto',
      'stats_detected_times': 'Rilevato {count} volte',
      'stats_destination': 'Destinazione',
      'stats_analyzed_trips': 'Viaggi analizzati: {count}',
      'activate_monitoring': 'Attiva Monitoraggio',
      'station_not_monitored_msg': 'Questa stazione non è monitorata. Vuoi aggiungerla manualmente al sistema di statistiche?',
      'cancel': 'Annulla',
      'delete': 'Elimina',
      'delete_all_offline_trains': 'Elimina tutti',
      'delete_all_offline_trains_title': 'Eliminare tutti i treni salvati?',
      'delete_all_offline_trains_desc': 'Verranno rimossi tutti i treni salvati offline su questo dispositivo.',
      'add_now': 'Aggiungi Ora',
      'stats_monitoring_title': 'Monitoraggio Statistiche',
      'stats_monitoring_msg': 'Questa stazione non è ancora inclusa nel sistema di tracciamento. Desideri attivarne il monitoraggio?\n\nNota: L\'elaborazione dei primi dati statistici non sarà immediata e richiederà del tempo per l\'accumulo delle informazioni sui treni.',
      'high': 'Alto',
      'medium': 'Medio',
      'low': 'Basso',
      'critical': 'Critico',
      'statistics': 'Statistiche',
      'train_stats_insights': 'Insight Operativi',
      'train_stats_timeline': 'Timeline Giornaliera',
      'train_stats_reliability': 'Punteggio Affidabilità',
      'train_stats_bottleneck': 'Collo di Bottiglia',
      'train_stats_worst_day': 'Giorno Peggiore',
      'train_stats_trend': 'Tendenza',
      'train_stats_streak': 'Giorni Consecutivi',
      'train_stats_no_data': 'Nessun dato storico disponibile.',
      'train_stats_max_delay': 'Ritardo Max',
      'train_stats_behavior': 'Comportamento',
      'train_stats_arr': 'Arr',
      'train_stats_dep': 'Part',
      'train_stats_platform': 'Bin',
      'train_stats_stops_analysis': 'Analisi Fermate (Storico)',
      'train_stats_avg_delay': '{delay} min ritardo medio',
      'train_stats_cancellations': '{rate}% cancellazioni ({logs} rilevamenti)',
      'search_tab_station': 'Per Stazione',
      'search_tab_train': 'Per Treno',
      'search_train_hint': 'Cerca per numero (es. 9631)...',
      'search_train_subtitle': 'Cerca un treno per numero e vedi il tabellone live',
      'search_train_empty': 'Inserisci il numero del treno',
      'search_train_no_results': 'Nessun treno trovato per "{query}"',
      'search_train_category': 'Categoria',
      'search_train_number': 'Numero',
      'search_train_origin': 'Origine',
      'search_train_destination': 'Destinazione',
      'search_train_see_stats': 'Statistiche',
      'stations': 'Stazioni',
      'trains': 'Treni',
      'train_stats_total_trips': 'Basato su {count} corse',
      'train_stats_cancellation_rate': 'Tasso Cancellazioni',
      'train_stats_net_delay': 'Variazione in Marcia',
      'train_stats_net_delay_recovers': 'Recupera {min}m',
      'train_stats_net_delay_adds': 'Accumula +{min}m',
      'train_stats_net_delay_stable': 'Stabile',
      'train_stats_historical_worst': 'RECORD NEGATIVO ASSOLUTO',
      'train_stats_historical_delay': '+{min} min a {station}',
      'train_stats_historical_date': 'Registrato il {date}',
      'solutions': 'Soluzioni',
      'noStopsAvailable': 'Nessuna fermata disponibile',
      'noStopsAvailableDesc': 'I dettagli di questo treno non sono stati caricati.',
      'reloadStops': 'Ricarica',
      'loadingStops': '⏳ Caricamento fermate...',
      'missingTrainId': 'ID treno mancante',
      'loadingDetailsTimeout': 'Timeout durante il caricamento dei dettagli',
      'loadingDetailsError': 'Impossibile caricare i dettagli del treno (HTTP {statusCode})',
      'networkError': 'Errore di rete: {error}',
      'offlineModeBanner': "Modalità offline: il progresso del treno è basato sui dati salvati l'ultima volta.",
      'trainEarly': "Anticipo {delay}'",
      'trainOnTime': 'In Orario',
      'trainDelayed': '+{delay} min',
      'stopAlreadyPassed': 'già passata',
      'stopCurrent': 'attuale',
      'stopCancelled': 'annullata',
      'notifyUntil': 'Notifica fino a',
      'chooseStopFromList': 'Scegli una fermata dalla lista',
      'stopsListUnavailable': 'Lista fermate non disponibile. Verrà inviata una notifica generale.',
      'notificationPreview': 'Anteprima notifica',
      'notifyToSelectedStop': 'Notifica fino alla fermata selezionata',
      'notifyGeneral': 'Notifica generale',
      'disableNotificationsForThisTrain': 'Disattiva notifiche per questo treno',
      'notificationsDisabled': 'Notifiche disattivate',
      'notificationSet': 'Notifica impostata',
      'endpointCheckFailed': "Impossibile verificare l'endpoint per il paese: {country}",
      'endpointRequestFailed': "Richiesta endpoint fallita: {candidate} (codice {code})",
      'networkErrorEndpointCheck': "Errore di rete durante la verifica dell'endpoint",
      'cannotDetermineUrlSetCountry': "Impossibile determinare l'URL. Imposta il paese.",
      'nextStop': 'Prossima fermata: {stop}',
      'nextStopFallback': 'Prossima fermata: --',
      'trainAtStation': 'Treno in stazione: {station}',
      'currentState': 'Stato attuale: {state}',
      'inTransit': 'In transito',
      'platform': 'Binario: {platform}',
      'departingAt': 'In partenza alle {time}',
      'arrivingAt': 'In arrivo alle {time}',
      'stopCancelledNotif': '⚠️ La tua fermata ({stop}) è stata annullata.',
      'trainAtYourStation': '⚠️ Treno in stazione: {stop}. Ricordati di scendere.',
      'approachingYourStop': '⚠️ Sei in arrivo alla tua fermata: {stop}. Prossima discesa.',
      'arrivedAtStop': '🚩 Sei arrivato a {stop}. Ricordati di scendere dal treno!',
      'remainingStops': 'Fermate rimanenti: {count}',
      'trainLabel': 'Treno',
      'trainCategoryNumber': '{category} {number}',
      'trainRoute': '{origin} → {destination}',
      'scheduledLabel': 'Previsto',
      // --- National / Regional ---
      'tab_national': 'Nazionale',
      'tab_regionale': 'Regionale',
      'regional_providers_title': 'Operatori Regionali',
      'regional_providers_subtitle': 'Seleziona il tuo operatore ferroviario regionale',
      'regional_no_providers': 'Nessun operatore regionale disponibile per questo paese',
      'regional_provider_stations': 'Stazioni',
      'regional_provider_departures': 'Partenze',
      'regional_provider_arrivals': 'Arrivi',
      'regional_provider_trip': 'Dettaglio Treno',
      'regional_provider_lines': 'Linee',
      'regional_provider_news': 'Avvisi',
      'regional_provider_realtime': 'Tempo Reale',
      'regional_open_web': 'Apri sito web',
      'regional_loading': 'Caricamento operatori regionali...',
      'regional_error': 'Errore nel caricamento degli operatori regionali',
    }, // end IT
    'en': {
      // --- Routing ---
      'routing_details': 'Route Details',
      'routing_solutions': 'solutions',
      'routing_tab_overview': 'Overview',
      'routing_tab_segments': 'Segments',
      'routing_tab_stops': 'Stops',
      'routing_trains_used': 'Trains used',
      'routing_summary': 'Route summary',
      'routing_direct': 'DIRECT',
      'routing_changes': '{count} CHANGES',
      'routing_duration': 'Duration: {duration}',
      'routing_origin_hint': 'Where from? (e.g. Rome)',
      'routing_destination_hint': 'Where to? (e.g. Milan)',
      'routing_search_btn': 'Search Routes',
      'routing_empty': 'Enter your origin and destination to find the best routes.',
      'routing_no_results': 'No solutions found between these stations.',
      'routing_time_now': 'Now',
      'routing_time_label': 'Time',
      'routing_time_date_label': 'Date',
      
      // --- Existing keys ---
      'trip_stops_title': 'Trip Stops',
      'no_updates': 'No updates',
      'trip_stops_unavailable': 'Stop details not available for {provider}',
      'live': 'LIVE',
      'details_and_position': 'Details & Position',
      'press_for_info': 'Press for info',
      'destination_na': 'Destination N/A',
      'filter_all': 'All',
      'filter_stops': 'Stops',
      'filter_trains': 'Trains',
      'filter_buses': 'Buses',
      'favorites': 'Favorites',
      'automatic': 'Automatic',
      'device_language': 'Device language',
      'settings_header_title': 'Settings',
      'settings_header_subtitle': 'Customize language, theme, and updates in a few taps.',
      'settings_language': 'Language',
      'settings_theme': 'Theme',
      'settings_auto_refresh': 'Auto refresh',
      'settings_configuration': 'Configuration',
      'settings_notifications': 'Notifications',
      'settings_ui': 'UI experience',
      'settings_map': 'Map',
      'settings_map_style': 'Map style',
      'settings_offline_sync': 'Offline sync',
      'settings_disclaimer': 'Info and disclaimer',
      'importantInfo': 'Important Info',
      'map': 'Map',
      'update': 'Update',
      'offline': 'Offline',
      'save_offline': 'Save offline',
      'offline_mode': 'Offline',
      'train_saved_offline': 'Train saved for offline mode',
      'train_saved_manual_offline': 'Train saved manually (offline auto-sync disabled)',
      'alerts': 'Alerts',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'auto': 'Auto',
      'off': 'Off',
      'managed_by_server': 'Managed by the server based on traffic',
      'map_style_dark': 'Dark',
      'map_style_light': 'Light',
      'map_style_streets': 'Streets',
      'map_style_satellite': 'Satellite',
      'map_style_satellite_streets': 'Sat+Streets',
      'other': 'Other',
      'custom_style_url': 'Custom style URL',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test Notifications',
      'train_notifications_config': 'Train notifications setup',
      'bus_notifications_config': 'Bus notifications setup',
      'station_id': 'Station ID',
      'provider': 'Provider',
      'base_url_optional': 'Base URL (optional)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Train arrival pre-notice',
      'train_arrival_pre_notice_desc': 'Get an alert N minutes before the estimated arrival at your stop (5–20 minutes).',
      'vector_train_logos': 'Vector train logos',
      'vector_train_logos_desc': 'Download and display official logos for train categories (for example Frecciarossa, Intercity) instead of plain text.',
      'update_configuration': 'Update Configuration',
      'update_provider_configuration': 'Update provider configuration',
      'configuration_update_desc': 'Download the latest bus provider configuration from the server',
      'configuration_updated_success': 'Configuration updated successfully',
      'offline_sync_title': 'Offline Sync',
      'offline_sync_desc': 'Automatically download route and schedule data when you sync from a city. The data will be stored locally and available even without connection.',
      'disclaimer_title': 'BC Transporter Does Not Replace Official Channels',
      'disclaimer_text': 'This application is not intended to replace the official platforms of rail companies or their sales channels. BC Transporter provides tracking information and data for informational purposes only.\n\nFor ticket purchases and to verify availability, fares, travel conditions, and official confirmations, always use the official channels of the rail companies (websites, official apps, authorized agencies, or certified resellers).\n\nTickets must be purchased through official platforms; BC Transporter does not sell tickets and does not replace official sales channels.\n\nWe are not responsible for purchases made through unofficial channels or for outdated price/condition information. Any links to third-party sites are provided for convenience only and do not imply endorsement or partnership.',
      'language_italian': 'Italian',
      'language_english': 'English',
      'language_german': 'German',
      'explore': 'Explore',
      'greeting': 'Hi, {name} 👋',
      'ready_to_go': 'Ready to go?',
      'refresh_realtime_tooltip': 'Refresh real-time data',
      'train_removed_favorites': 'Train removed from favorites',
      'error_removing_favorite': 'Error removing favorite',
      'undo': 'Undo',
      'train_added_favorites': 'Train added to favorites',
      'error_adding_favorite': 'Error adding favorite',
      'no_route_for_line': 'No route available for line {line}',
      'upcoming_departures': 'Upcoming Departures',
      'remove_from_favorites': 'Remove from favorites',
      'add_to_favorites': 'Add to favorites',
      'guest': 'Guest',
      'where_to_go_today': 'Where do you want to go today?',
      'explore_map': 'Explore the Map',
      'explore_map_desc': 'View buses and trains in real time on the interactive map.',
      'service_status': 'Service Status',
      'status_regular': 'Regular',
      'status_delays': 'Delays',
      'your_favorites': 'Your Favorites',
      'see_all': 'View all',
      'no_favorites_saved': 'No saved favorites',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'quick_actions_title': 'Quick actions',
      'action_map': 'Map',
      'action_ticket': 'Tickets',
      'action_routes': 'Routes',
      'action_alerts': 'Alerts',
      'planes_label': 'Planes',
      'today_badge': 'TODAY',
      'change_btn': 'Change',
      'weather_unavailable': 'Weather unavailable',
      'bus_stop_label': 'Bus stop',
      'station_label': 'Station',
      'local_label': 'Local',
      'your_position': 'Your location',
      'select_city': 'Select city',
      'search_city_weather': 'Search your city for the weather',
      'city_search_hint': 'e.g. Milan, Paris, London…',
      'use_my_position': 'Use my location',
      'detecting_gps': 'Locating…',
      'auto_detect_gps': 'Auto-detect via GPS',
      'search_results_label': 'Search results',
      'no_city_found': 'No city found',
      'type_city_name': 'Start typing the\ncity name',
      'permission_denied_location': 'Location permission denied. Enable it in settings.',
      'gps_unavailable': 'Unable to detect GPS location',
      'logo_source': 'Logo source',
      'logos_official': 'Official',
      'logos_custom': 'Custom',
      'share_trip': 'Share',
      'share_trip_msg': 'Follow my trip live',
      'share_failed': 'Share failed, try again',
      'shared_trip': 'Shared trip',
      'trip_not_found': 'Trip not found',
      'trip_expired': 'This link has expired',
      'trip_load_error': 'Network error, try again',
      'estimated_label': 'Estimated',
      'stops_title': 'Stops',
      'delay_minutes': 'Delay: {minutes} min',
      'early_minutes': 'Early: {minutes} min',
      'on_time': 'On time',
      'remaining_stops': 'Remaining stops: {count}',
      'notify_until': 'Notify until...',
      'choose_stop_from_list': 'Choose a stop from the list',
      'stops_list_unavailable_general_notification': 'Stop list unavailable, using general notification.',
      'notification_preview': 'Notification preview',
      'notify_to_selected_stop': 'Notify until selected stop',
      'notify_general': 'General notification',
      'arrivals': 'Arrivals',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Delay',
      'origin': 'Origin',
      'destination': 'Destination',
      'est_prefix': 'Est: {time}',
      'in_transit': 'In transit',
      'on_time_small': 'On time',
      'loading': 'Loading...',
      'delay_short': '+{minutes}min',
      'notifications': 'Notifications',
      'notifications_disabled': 'Notifications disabled',
      'notification_set': 'Notification set',
      'endpoint_check_failed_country': 'Unable to verify endpoint from selected country',
      'endpoint_request_failed': 'Request to endpoint {candidate} failed: HTTP {code}',
      'network_error_endpoint_check': 'Network error while checking endpoint',
      'cannot_determine_url_set_country': 'Cannot determine exact URL: set the panel country or use manual endpoint',
      'disable_notifications_for_this_train': 'Disable notifications for this train',
      'retry': 'Retry',
      'messages': 'Messages',
      'close': 'Close',
      'cancelled': 'Cancelled',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'PLT',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Login to see favorites',
      'login': 'Login',
      'register': 'Register',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'No monitored stops',
      'vehicle_info': 'Vehicle Info',
      'vehicle_id': 'Vehicle ID',
      'line': 'Line',
      'destination_label': 'Destination',
      'speed_label': 'Speed',
      'heading_label': 'Heading',
      'operator_label': 'Operator',
      'trip_id_label': 'Trip ID',
      'refresh_label': 'Refresh',
      'cancel_notification_label': 'Cancel notification',
      'remove_label': 'Remove',
      'no_monitored_stations': 'No monitored stations',
      'no_monitored_trains': 'No monitored trains',
      'url_label': 'URL',
      'country_label': 'Country',
      'force_refresh': 'Force refresh',
      'notification_cancelled': 'Notification cancelled',
      'updated_at': 'Updated: {time}',
      'select_item': 'Select {label}',
      'stop_of': 'Stop of {provider}',
      'saved': 'Saved',
      'favorite_action': 'Favorite',
      'train_not_found': 'Train {number} not found',
      'train_label': 'Train {number}',
      'na': 'N/A',
      'unknown': 'Unknown',
      'stop_not_found': 'Stop "{name}" not found',
      'messages_count': 'Messages: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Oops! Something went wrong',
      'arrival': 'Arrival',
      'departure': 'Departure',
      'no_bus_scheduled': 'No buses scheduled',
      'scheduled_label': 'Scheduled',
      'stats_station_title': 'Station Statistics',
      'stats_day': 'Day',
      'stats_week': 'Week',
      'stats_month': 'Month',
      'stats_year': 'Year',
      'stats_date_of': 'Data: {date}',
      'stats_punctuality': 'Punctuality',
      'stats_avg_delay': 'Average Delay',
      'stats_total_trains': 'Total Trains',
      'stats_cancelled_trains': 'Cancelled Trains',
      'stats_movements_analysis': 'Movements Analysis',
      'stats_arrivals': 'Arrivals',
      'stats_departures': 'Departures',
      'stats_avg_delay_short': 'Avg Delay',
      'stats_punctuality_short': 'Punctuality',
      'stats_hourly_trend': 'Hourly Delay Trend',
      'stats_historical_trend': 'Historical Delay Trend',
      'stats_category_perf': 'Performance by Category',
      'stats_worst_trains': 'Worst Performing Trains',
      'stats_worst_routes': 'Worst Performing Routes',
      'stats_no_data': 'No data available',
      'stats_no_chart_data': 'No data for chart',
      'stats_avg_delay_val': 'Avg Delay: {val}m',
      'stats_punctuality_val': '{val}% punctuality',
      'stats_unknown_train': 'Unknown Train',
      'stats_detected_times': 'Detected {count} times',
      'stats_destination': 'Destination',
      'stats_analyzed_trips': 'Analyzed trips: {count}',
      'activate_monitoring': 'Activate Monitoring',
      'station_not_monitored_msg': 'This station is not monitored. Do you want to add it manually to the statistics system?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'delete_all_offline_trains': 'Delete all',
      'delete_all_offline_trains_title': 'Delete all saved trains?',
      'delete_all_offline_trains_desc': 'All trains saved offline on this device will be removed.',
      'add_now': 'Add Now',
      'stats_monitoring_title': 'Statistics Monitoring',
      'stats_monitoring_msg': 'This station is not yet included in the tracking system. Do you want to activate monitoring for it?\n\nNote: The processing of the first statistical data will not be immediate and will require time to accumulate train information.',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'critical': 'Critical',
      'statistics': 'Statistics',
      'train_stats_insights': 'Operational Insights',
      'train_stats_timeline': 'Daily Timeline',
      'train_stats_reliability': 'Reliability Score',
      'train_stats_bottleneck': 'Bottleneck',
      'train_stats_worst_day': 'Worst Day',
      'train_stats_trend': 'Trend',
      'train_stats_streak': 'Streak (Days)',
      'train_stats_no_data': 'No historical data available.',
      'train_stats_max_delay': 'Max Delay',
      'train_stats_behavior': 'Behavior',
      'train_stats_arr': 'Arr',
      'train_stats_dep': 'Dep',
      'train_stats_platform': 'Plat',
      'train_stats_stops_analysis': 'Stops Analysis (Historical)',
      'train_stats_avg_delay': '{delay} min average delay',
      'train_stats_cancellations': '{rate}% cancellations ({logs} logs)',
      'search_tab_station': 'By Station',
      'search_tab_train': 'By Train',
      'search_train_hint': 'Search by number (e.g. 9631)...',
      'search_train_subtitle': 'Search a train by number and see the live board',
      'search_train_empty': 'Enter the train number',
      'search_train_no_results': 'No train found for "{query}"',
      'search_train_category': 'Category',
      'search_train_number': 'Number',
      'search_train_origin': 'Origin',
      'search_train_destination': 'Destination',
      'search_train_see_stats': 'Statistics',
      'stations': 'Stations',
      'trains': 'Trains',
      'train_stats_total_trips': 'Based on {count} trips',
      'train_stats_cancellation_rate': 'Cancellation Rate',
      'train_stats_net_delay': 'In-Transit Delay',
      'train_stats_net_delay_recovers': 'Recovers {min}m',
      'train_stats_net_delay_adds': 'Accumulates +{min}m',
      'train_stats_net_delay_stable': 'Stable',
      'train_stats_historical_worst': 'ALL-TIME WORST RECORD',
      'train_stats_historical_delay': '+{min} min at {station}',
      'train_stats_historical_date': 'Recorded on {date}',
      'solutions': 'Solutions',
      'noStopsAvailable': 'No stops available',
      'noStopsAvailableDesc': 'Details for this train have not been loaded.',
      'reloadStops': 'Reload',
      'loadingStops': '⏳ Loading stops...',
      'missingTrainId': 'Missing train ID',
      'loadingDetailsTimeout': 'Timeout while loading details',
      'loadingDetailsError': 'Unable to load train details (HTTP {statusCode})',
      'networkError': 'Network error: {error}',
      'offlineModeBanner': 'Offline mode: train progress is based on data saved last time.',
      'trainEarly': "Early by {delay}'",
      'trainOnTime': 'On Time',
      'trainDelayed': '+{delay} min',
      'stopAlreadyPassed': 'already passed',
      'stopCurrent': 'current',
      'stopCancelled': 'cancelled',
      'notifyUntil': 'Notify until',
      'chooseStopFromList': 'Choose a stop from the list',
      'stopsListUnavailable': 'Stops list unavailable. A general notification will be sent.',
      'notificationPreview': 'Notification preview',
      'notifyToSelectedStop': 'Notify until selected stop',
      'notifyGeneral': 'General notification',
      'disableNotificationsForThisTrain': 'Disable notifications for this train',
      'notificationsDisabled': 'Notifications disabled',
      'notificationSet': 'Notification set',
      'endpointCheckFailed': 'Could not verify endpoint for country: {country}',
      'endpointRequestFailed': 'Endpoint request failed: {candidate} (code {code})',
      'networkErrorEndpointCheck': 'Network error during endpoint verification',
      'cannotDetermineUrlSetCountry': 'Cannot determine URL. Set the country.',
      'nextStop': 'Next stop: {stop}',
      'nextStopFallback': 'Next stop: --',
      'trainAtStation': 'Train at station: {station}',
      'currentState': 'Current state: {state}',
      'inTransit': 'In transit',
      'platform': 'Platform: {platform}',
      'departingAt': 'Departing at {time}',
      'arrivingAt': 'Arriving at {time}',
      'stopCancelledNotif': '⚠️ Your stop ({stop}) has been cancelled.',
      'trainAtYourStation': '⚠️ Train at station: {stop}. Remember to get off.',
      'approachingYourStop': '⚠️ Approaching your stop: {stop}. Next descent.',
      'arrivedAtStop': '🚩 You arrived at {stop}. Remember to get off the train!',
      'remainingStops': 'Remaining stops: {count}',
      'trainLabel': 'Train',
      'trainCategoryNumber': '{category} {number}',
      'trainRoute': '{origin} → {destination}',
      'scheduledLabel': 'Scheduled',
      // --- National / Regional ---
      'tab_national': 'National',
      'tab_regionale': 'Regional',
      'regional_providers_title': 'Regional Operators',
      'regional_providers_subtitle': 'Select your regional railway operator',
      'regional_no_providers': 'No regional operators available for this country',
      'regional_provider_stations': 'Stations',
      'regional_provider_departures': 'Departures',
      'regional_provider_arrivals': 'Arrivals',
      'regional_provider_trip': 'Trip Details',
      'regional_provider_lines': 'Lines',
      'regional_provider_news': 'News',
      'regional_provider_realtime': 'Realtime',
      'regional_open_web': 'Open website',
      'regional_loading': 'Loading regional operators...',
      'regional_error': 'Error loading regional operators',
    },
    'de': {
      // --- Routing ---
      'routing_details': 'Verbindungsdetails',
      'routing_solutions': 'Verbindungen',
      'routing_tab_overview': 'Übersicht',
      'routing_tab_segments': 'Abschnitte',
      'routing_tab_stops': 'Haltestellen',
      'routing_trains_used': 'Verwendete Züge',
      'routing_summary': 'Zusammenfassung',
      'routing_direct': 'DIREKT',
      'routing_changes': '{count} UMSTIEGE',
      'routing_duration': 'Dauer: {duration}',
      'routing_origin_hint': 'Von wo? (z.B. Rom)',
      'routing_destination_hint': 'Wohin? (z.B. Mailand)',
      'routing_search_btn': 'Verbindungen suchen',
      'routing_empty': 'Start und Ziel eingeben, um die besten Routen zu finden.',
      'routing_no_results': 'Keine Verbindungen zwischen diesen Bahnhöfen gefunden.',
      'routing_time_now': 'Jetzt',
      'routing_time_label': 'Zeit',
      'routing_time_date_label': 'Datum',
      
      // --- Existing keys ---
      'trip_stops_title': 'Haltestellen der Fahrt',
      'no_updates': 'Keine Aktualisierungen',
      'trip_stops_unavailable': 'Haltestellendetails nicht verfügbar für {provider}',
      'live': 'LIVE',
      'details_and_position': 'Details & Position',
      'press_for_info': 'Zum Anzeigen tippen',
      'destination_na': 'Ziel N/V',
      'filter_all': 'Alle',
      'filter_stops': 'Haltestellen',
      'filter_trains': 'Züge',
      'filter_buses': 'Busse',
      'favorites': 'Favoriten',
      'automatic': 'Automatisch',
      'device_language': 'Gerätesprache',
      'settings_header_title': 'Einstellungen',
      'settings_header_subtitle': 'Sprache, Design und Aktualisierungen mit wenigen Tipps anpassen.',
      'settings_language': 'Sprache',
      'settings_theme': 'Design',
      'settings_auto_refresh': 'Automatische Aktualisierung',
      'settings_configuration': 'Konfiguration',
      'settings_notifications': 'Benachrichtigungen',
      'settings_ui': 'UI-Erlebnis',
      'settings_map': 'Karte',
      'settings_map_style': 'Kartenstil',
      'settings_offline_sync': 'Offline-Synchronisierung',
      'settings_disclaimer': 'Informationen und Hinweis',
      'importantInfo': 'Wichtige Informationen',
      'map': 'Karte',
      'update': 'Aktualisieren',
      'offline': 'Offline',
      'save_offline': 'Offline speichern',
      'offline_mode': 'Offline',
      'train_saved_offline': 'Zug für den Offline-Modus gespeichert',
      'train_saved_manual_offline': 'Zug manuell gespeichert (Offline-Autosync deaktiviert)',
      'alerts': 'Hinweise',
      'theme_light': 'Hell',
      'theme_dark': 'Dunkel',
      'theme_system': 'System',
      'auto': 'Auto',
      'off': 'Aus',
      'managed_by_server': 'Vom Server basierend auf dem Verkehr verwaltet',
      'map_style_dark': 'Dunkel',
      'map_style_light': 'Hell',
      'map_style_streets': 'Straßen',
      'map_style_satellite': 'Satellit',
      'map_style_satellite_streets': 'Sat+Straßen',
      'other': 'Andere',
      'custom_style_url': 'Benutzerdefinierte Stil-URL',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test-Benachrichtigungen',
      'train_notifications_config': 'Zug-Benachrichtigungen konfigurieren',
      'bus_notifications_config': 'Bus-Benachrichtigungen konfigurieren',
      'station_id': 'Station-ID',
      'provider': 'Anbieter',
      'base_url_optional': 'Basis-URL (optional)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Vorabhinweis Zugankunft',
      'train_arrival_pre_notice_desc': 'Erhalte eine Benachrichtigung N Minuten vor der geschätzten Ankunft an deiner Haltestelle (5–20 Minuten).',
      'vector_train_logos': 'Vektor-Zuglogos',
      'vector_train_logos_desc': 'Offizielle Logos für Zugkategorien herunterladen und anzeigen (z. B. Frecciarossa, Intercity) statt nur Text.',
      'update_configuration': 'Konfiguration aktualisieren',
      'update_provider_configuration': 'Anbieter-Konfiguration aktualisieren',
      'configuration_update_desc': 'Die neueste Bus-Anbieterkonfiguration vom Server herunterladen',
      'configuration_updated_success': 'Konfiguration erfolgreich aktualisiert',
      'offline_sync_title': 'Offline-Synchronisierung',
      'offline_sync_desc': 'Routen- und Fahrplandaten automatisch herunterladen, wenn du von einer Stadt synchronisierst. Die Daten werden lokal gespeichert und sind auch ohne Verbindung verfügbar.',
      'disclaimer_title': 'BC Transporter Ersetzt Nicht die Offiziellen Kanäle',
      'disclaimer_text': 'Diese Anwendung ist nicht dazu bestimmt, die offiziellen Plattformen der Bahnunternehmen oder deren Verkaufskanäle zu ersetzen. BC Transporter stellt Tracking-Informationen und Daten ausschließlich zu Informationszwecken bereit.\n\nFür Ticketkäufe und zur Überprüfung von Verfügbarkeit, Preisen, Reisebedingungen und offiziellen Bestätigungen nutze bitte immer die offiziellen Kanäle der Bahnunternehmen (Websites, offizielle Apps, autorisierte Agenturen oder zertifizierte Wiederverkäufer).\n\nTickets müssen über die offiziellen Plattformen gekauft werden; BC Transporter verkauft keine Tickets und ersetzt nicht die offiziellen Verkaufskanäle.\n\nWir übernehmen keine Verantwortung für Käufe über inoffizielle Kanäle oder für veraltete Preis-/Bedingungsinformationen. Links zu Drittanbietern dienen nur der Bequemlichkeit und bedeuten keine Empfehlung oder Partnerschaft.',
      'language_italian': 'Italienisch',
      'language_english': 'Englisch',
      'language_german': 'Deutsch',
      'explore': 'Entdecken',
      'greeting': 'Hallo, {name} 👋',
      'ready_to_go': 'Bereit loszufahren?',
      'refresh_realtime_tooltip': 'Echtzeitdaten aktualisieren',
      'train_removed_favorites': 'Zug aus Favoriten entfernt',
      'error_removing_favorite': 'Fehler beim Entfernen des Favoriten',
      'undo': 'Rückgängig',
      'train_added_favorites': 'Zug zu Favoriten hinzugefügt',
      'error_adding_favorite': 'Fehler beim Hinzufügen',
      'no_route_for_line': 'Keine Route verfügbar für Linie {line}',
      'upcoming_departures': 'Nächste Abfahrten',
      'remove_from_favorites': 'Aus Favoriten entfernen',
      'add_to_favorites': 'Zu Favoriten hinzufügen',
      'guest': 'Gast',
      'where_to_go_today': 'Wohin möchtest du heute fahren?',
      'explore_map': 'Karte erkunden',
      'explore_map_desc': 'Zeigt Busse und Züge in Echtzeit auf der interaktiven Karte an.',
      'service_status': 'Betriebsstatus',
      'status_regular': 'Regulär',
      'status_delays': 'Verspätungen',
      'your_favorites': 'Deine Favoriten',
      'see_all': 'Alle ansehen',
      'no_favorites_saved': 'Keine Favoriten gespeichert',
      'greeting_morning': 'Guten Morgen',
      'greeting_afternoon': 'Guten Nachmittag',
      'greeting_evening': 'Guten Abend',
      'quick_actions_title': 'Schnellzugriff',
      'action_map': 'Karte',
      'action_ticket': 'Tickets',
      'action_routes': 'Routen',
      'action_alerts': 'Hinweise',
      'planes_label': 'Flugzeuge',
      'today_badge': 'HEUTE',
      'change_btn': 'Ändern',
      'weather_unavailable': 'Wetter nicht verfügbar',
      'bus_stop_label': 'Bushaltestelle',
      'station_label': 'Bahnhof',
      'local_label': 'Lokal',
      'your_position': 'Dein Standort',
      'select_city': 'Stadt auswählen',
      'search_city_weather': 'Suche deine Stadt für das Wetter',
      'city_search_hint': 'z.B. Mailand, Paris, London…',
      'use_my_position': 'Meinen Standort verwenden',
      'detecting_gps': 'Ortung läuft…',
      'auto_detect_gps': 'Automatisch per GPS erkennen',
      'search_results_label': 'Suchergebnisse',
      'no_city_found': 'Keine Stadt gefunden',
      'type_city_name': 'Beginne den\nStadtnamen zu tippen',
      'permission_denied_location': 'Standortberechtigung verweigert. Aktiviere sie in den Einstellungen.',
      'gps_unavailable': 'GPS-Position konnte nicht ermittelt werden',
      'logo_source': 'Logoquelle',
      'logos_official': 'Offiziell',
      'logos_custom': 'Benutzerdefiniert',
      'share_trip': 'Teilen',
      'share_trip_msg': 'Verfolge meine Fahrt live',
      'share_failed': 'Teilen fehlgeschlagen, erneut versuchen',
      'shared_trip': 'Geteilte Fahrt',
      'trip_not_found': 'Fahrt nicht gefunden',
      'trip_expired': 'Dieser Link ist abgelaufen',
      'trip_load_error': 'Netzwerkfehler, erneut versuchen',
      'estimated_label': 'Voraussichtlich',
      'stops_title': 'Haltestellen',
      'delay_minutes': 'Verspätung: {minutes} min',
      'early_minutes': 'Früh: {minutes} min',
      'on_time': 'Pünktlich',
      'remaining_stops': 'Verbleibende Haltestellen: {count}',
      'notify_until': 'Benachrichtigen bis...',
      'choose_stop_from_list': 'Wähle eine Haltestelle aus der Liste',
      'stops_list_unavailable_general_notification': 'Haltestellenliste nicht verfügbar, allgemeine Benachrichtigung wird verwendet.',
      'notification_preview': 'Benachrichtigungs-Vorschau',
      'notify_to_selected_stop': 'Benachrichtigen bis zur ausgewählten Haltestelle',
      'notify_general': 'Allgemeine Benachrichtigung',
      'arrivals': 'Ankünfte',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Verspätung',
      'origin': 'Abfahrt',
      'destination': 'Ziel',
      'est_prefix': 'Est: {time}',
      'in_transit': 'Unterwegs',
      'on_time_small': 'Pünktlich',
      'loading': 'Lädt...',
      'delay_short': '+{minutes}min',
      'notifications': 'Benachrichtigungen',
      'notifications_disabled': 'Benachrichtigungen deaktiviert',
      'notification_set': 'Benachrichtigung gesetzt',
      'endpoint_check_failed_country': 'Endpunkt konnte aus dem ausgewählten Land nicht überprüft werden',
      'endpoint_request_failed': 'Anforderung an Endpunkt {candidate} fehlgeschlagen: HTTP {code}',
      'network_error_endpoint_check': 'Netzwerkfehler beim Überprüfen des Endpunkts',
      'cannot_determine_url_set_country': 'URL kann nicht bestimmt werden: Setze das Land im Panel oder verwende den manuellen Endpunkt',
      'disable_notifications_for_this_train': 'Benachrichtigungen für diesen Zug deaktivieren',
      'retry': 'Erneut versuchen',
      'messages': 'Nachrichten',
      'close': 'Schließen',
      'cancelled': 'Abgesagt',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'BIN',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Anmelden, um Favoriten zu sehen',
      'login': 'Anmelden',
      'register': 'Registrieren',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'Keine überwachten Haltestellen',
      'vehicle_info': 'Fahrzeuginfo',
      'vehicle_id': 'Fahrzeug-ID',
      'line': 'Linie',
      'destination_label': 'Ziel',
      'speed_label': 'Geschwindigkeit',
      'heading_label': 'Richtung',
      'stats_station_title': 'Stationsstatistiken',
      'stats_day': 'Tag',
      'stats_week': 'Woche',
      'stats_month': 'Monat',
      'stats_year': 'Jahr',
      'stats_date_of': 'Datum: {date}',
      'stats_punctuality': 'Pünktlichkeit',
      'stats_avg_delay': 'Durchschnittliche Verspätung',
      'stats_total_trains': 'Gesamtzüge',
      'stats_cancelled_trains': 'Ausgefallene Züge',
      'stats_movements_analysis': 'Bewegungsanalyse',
      'stats_arrivals': 'Ankünfte',
      'stats_departures': 'Abfahrten',
      'stats_avg_delay_short': 'Durchschn. Versp.',
      'stats_punctuality_short': 'Pünktlichkeit',
      'stats_hourly_trend': 'Stündlicher Verspätungstrend',
      'stats_historical_trend': 'Historischer Verspätungstrend',
      'stats_category_perf': 'Leistung nach Kategorie',
      'stats_worst_trains': 'Züge mit den größten Verspätungen',
      'stats_worst_routes': 'Strecken mit den größten Verspätungen',
      'stats_no_data': 'Keine Daten verfügbar',
      'stats_no_chart_data': 'Keine Daten für das Diagramm',
      'stats_avg_delay_val': 'Durchschn. Versp.: {val}m',
      'stats_punctuality_val': '{val}% Pünktlichkeit',
      'stats_unknown_train': 'Unbekannter Zug',
      'stats_detected_times': 'Erkannt {count} Mal',
      'stats_destination': 'Ziel',
      'stats_analyzed_trips': 'Analysierte Fahrten: {count}',
      'operator_label': 'Betreiber',
      'trip_id_label': 'Fahrt-ID',
      'refresh_label': 'Aktualisieren',
      'cancel_notification_label': 'Benachrichtigung löschen',
      'remove_label': 'Entfernen',
      'no_monitored_stations': 'Keine überwachten Stationen',
      'no_monitored_trains': 'Keine überwachten Züge',
      'url_label': 'URL',
      'country_label': 'Land',
      'force_refresh': 'Erzwungene Aktualisierung',
      'notification_cancelled': 'Benachrichtigung gelöscht',
      'updated_at': 'Aktualisiert: {time}',
      'select_item': 'Wähle {label}',
      'stop_of': 'Haltestelle von {provider}',
      'saved': 'Gespeichert',
      'favorite_action': 'Favorit',
      'train_not_found': 'Zug {number} nicht gefunden',
      'train_label': 'Zug {number}',
      'na': 'N/V',
      'unknown': 'Unbekannt',
      'stop_not_found': 'Haltestelle "{name}" nicht gefunden',
      'messages_count': 'Nachrichten: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Hoppla! Etwas ist schief gelaufen',
      'arrival': 'Ankunft',
      'departure': 'Abfahrt',
      'no_bus_scheduled': 'Keine Busse geplant',
      'scheduled_label': 'Geplant',
      'activate_monitoring': 'Überwachung aktivieren',
      'station_not_monitored_msg': 'Dieser Bahnhof wird nicht überwacht. Möchten Sie ihn manuell zum Statistiksystem hinzufügen?',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'delete_all_offline_trains': 'Alle löschen',
      'delete_all_offline_trains_title': 'Alle gespeicherten Züge löschen?',
      'delete_all_offline_trains_desc': 'Alle offline gespeicherten Züge auf diesem Gerät werden entfernt.',
      'add_now': 'Jetzt hinzufügen',
      'stats_monitoring_title': 'Statistik-Überwachung',
      'stats_monitoring_msg': 'Dieser Bahnhof ist noch nicht im Tracking-System enthalten. Möchten Sie die Überwachung dafür aktivieren?\n\nHinweis: Die Verarbeitung der ersten statistischen Daten erfolgt nicht sofort und erfordert Zeit, um Zuginformationen zu sammeln.',
      'high': 'Hoch',
      'medium': 'Mittel',
      'low': 'Niedrig',
      'critical': 'Kritisch',
      'statistics': 'Statistiken',
      'train_stats_insights': 'Betriebliche Einblicke',
      'train_stats_timeline': 'Tägliche Zeitleiste',
      'train_stats_reliability': 'Zuverlässigkeitsbewertung',
      'train_stats_bottleneck': 'Engpass',
      'train_stats_worst_day': 'Schlechtester Tag',
      'train_stats_trend': 'Trend',
      'train_stats_streak': 'Tage in Folge',
      'train_stats_no_data': 'Keine historischen Daten verfügbar.',
      'train_stats_max_delay': 'Max. Verspätung',
      'train_stats_behavior': 'Verhalten',
      'train_stats_arr': 'Ank',
      'train_stats_dep': 'Abf',
      'train_stats_platform': 'Gleis',
      'train_stats_stops_analysis': 'Haltestellenanalyse (Historisch)',
      'train_stats_avg_delay': '{delay} Min. Durchschnittliche Verspätung',
      'train_stats_cancellations': '{rate}% Ausfälle ({logs} Erfassungen)',
      'search_tab_station': 'Nach Bahnhof',
      'search_tab_train': 'Nach Zug',
      'search_train_hint': 'Nach Nummer suchen (z.B. 9631)...',
      'search_train_subtitle': 'Zug nach Nummer suchen und live Tafel anzeigen',
      'search_train_empty': 'Zugnummer eingeben',
      'search_train_no_results': 'Kein Zug gefunden für "{query}"',
      'search_train_category': 'Kategorie',
      'search_train_number': 'Nummer',
      'search_train_origin': 'Herkunft',
      'search_train_destination': 'Ziel',
      'search_train_see_stats': 'Statistiken',
      'stations': 'Bahnhöfe',
      'trains': 'Züge',
      'train_stats_total_trips': 'Basierend auf {count} Fahrten',
      'train_stats_cancellation_rate': 'Ausfallquote',
      'train_stats_net_delay': 'Verspätungsänderung',
      'train_stats_net_delay_recovers': 'Holt {min}m auf',
      'train_stats_net_delay_adds': 'Sammelt +{min}m an',
      'train_stats_net_delay_stable': 'Stabil',
      'train_stats_historical_worst': 'HISTORISCHER NEGATIVREKORD',
      'train_stats_historical_delay': '+{min} Min. bei {station}',
      'train_stats_historical_date': 'Aufgezeichnet am {date}',
      'solutions': 'Verbindungen',
      'noStopsAvailable': 'Keine Haltestellen verfügbar',
      'noStopsAvailableDesc': 'Details für diesen Zug wurden nicht geladen.',
      'reloadStops': 'Neu laden',
      'loadingStops': '⏳ Haltestellen werden geladen...',
      'missingTrainId': 'Fehlende Zug-ID',
      'loadingDetailsTimeout': 'Timeout beim Laden der Details',
      'loadingDetailsError': 'Zugdetails konnten nicht geladen werden (HTTP {statusCode})',
      'networkError': 'Netzwerkfehler: {error}',
      'offlineModeBanner': 'Offline-Modus: Der Trainfortschritt basiert zuletzt gespeicherten Daten.',
      'trainEarly': "Früh um {delay}'",
      'trainOnTime': 'Pünktlich',
      'trainDelayed': '+{delay} min',
      'stopAlreadyPassed': 'bereits vorbei',
      'stopCurrent': 'aktuell',
      'stopCancelled': 'storniert',
      'notifyUntil': 'Benachrichtigen bis',
      'chooseStopFromList': 'Wählen Sie eine Haltestelle aus der Liste',
      'stopsListUnavailable': 'Haltestellenliste nicht verfügbar. Eine allgemeine Benachrichtigung wird gesendet.',
      'notificationPreview': 'Benachrichtigungsvorschau',
      'notifyToSelectedStop': 'Benachrichtigen bis zur ausgewählten Haltestelle',
      'notifyGeneral': 'Allgemeine Benachrichtigung',
      'disableNotificationsForThisTrain': 'Benachrichtigungen für diesen Zug deaktivieren',
      'notificationsDisabled': 'Benachrichtigungen deaktiviert',
      'notificationSet': 'Benachrichtigung eingestellt',
      'endpointCheckFailed': 'Endpunkt konnte nicht überprüft werden für Land: {country}',
      'endpointRequestFailed': 'Endpunktanfrage fehlgeschlagen: {candidate} (Code {code})',
      'networkErrorEndpointCheck': 'Netzwerkfehler bei der Endpunktüberprüfung',
      'cannotDetermineUrlSetCountry': 'URL kann nicht bestimmt werden. Land einstellen.',
      'nextStop': 'Nächste Haltestelle: {stop}',
      'nextStopFallback': 'Nächste Haltestelle: --',
      'trainAtStation': 'Zug im Bahnhof: {station}',
      'currentState': 'Aktueller Status: {state}',
      'inTransit': 'Unterwegs',
      'platform': 'Gleis: {platform}',
      'departingAt': 'Abfahrt um {time}',
      'arrivingAt': 'Ankunft um {time}',
      'stopCancelledNotif': '⚠️ Ihre Haltestelle ({stop}) wurde storniert.',
      'trainAtYourStation': '⚠️ Zug im Bahnhof: {stop}. Denken Sie ans Aussteigen.',
      'approachingYourStop': '⚠️ Nähert sich Ihrer Haltestelle: {stop}. Nächster Halt.',
      'arrivedAtStop': '🚩 Sie sind angekommen in {stop}. Denken Sie ans Aussteigen!',
      'remainingStops': 'Verbleibende Haltestellen: {count}',
      'trainLabel': 'Zug',
      'trainCategoryNumber': '{category} {number}',
      'trainRoute': '{origin} → {destination}',
      'scheduledLabel': 'Geplant',
      // --- National / Regional ---
      'tab_national': 'National',
      'tab_regionale': 'Regional',
      'regional_providers_title': 'Regionale Anbieter',
      'regional_providers_subtitle': 'Wählen Sie Ihren regionalen Eisenbahnanbieter',
      'regional_no_providers': 'Keine regionalen Anbieter für dieses Land verfügbar',
      'regional_provider_stations': 'Bahnhöfe',
      'regional_provider_departures': 'Abfahrten',
      'regional_provider_arrivals': 'Ankünfte',
      'regional_provider_trip': 'Fahrtdetails',
      'regional_provider_lines': 'Linien',
      'regional_provider_news': 'Neuigkeiten',
      'regional_provider_realtime': 'Echtzeit',
      'regional_open_web': 'Webseite öffnen',
      'regional_loading': 'Regionale Anbieter laden...',
      'regional_error': 'Fehler beim Laden der regionalen Anbieter',
    }
  };

  static String t(BuildContext context, String key, {Map<String, String>? params, String? fallback}) {
    final settings = Provider.of<SettingsProvider>(context, listen: false);
    final code = settings.appLocale?.languageCode ?? Localizations.localeOf(context).languageCode;
    final map = _t[code] ?? _t['it']!;
    var res = map[key] ?? fallback ?? key;
    if (params != null && params.isNotEmpty) {
      params.forEach((k, v) {
        res = res.replaceAll('{$k}', v);
      });
    }
    return res;
  }
}