import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../../presentation/providers/settings_provider.dart';

class RuntimeLocalizations {
  // Minimal runtime translations for strings not present in ARB.
  static final Map<String, Map<String, String>> _t = {
    'it': {
      'trip_stops_title': 'Fermate del Viaggio',
      'no_updates': 'Nessun aggiornamento',
      'trip_stops_unavailable': 'Dettagli fermate non disponibili per {provider}',
      'live': 'LIVE',
      'details_and_position': 'Dettagli e Posizione',
      'press_for_info': 'Premi per info',
      'destination_na': 'Destinazione N/A',
      'filter_all': 'Tutti',
      'filter_stops': 'Fermate',
      'filter_trains': 'Treni',
      'filter_buses': 'Bus',
      'favorites': 'Preferiti',
      'automatic': 'Automatico',
      'device_language': 'Lingua del dispositivo',
      'settings_header_title': 'Impostazioni',
      'settings_header_subtitle': 'Personalizza lingua, tema e aggiornamenti in pochi tocchi.',
      'settings_language': 'Lingua',
      'settings_theme': 'Tema',
      'settings_auto_refresh': 'Aggiornamento automatico',
      'settings_configuration': 'Configurazione',
      'settings_notifications': 'Notifiche',
      'settings_ui': 'Esperienza UI',
      'settings_map': 'Mappa',
      'settings_map_style': 'Stile mappa',
      'settings_offline_sync': 'Sincronizzazione offline',
      'settings_disclaimer': 'Informazioni e disclaimer',
      'importantInfo': 'Informazioni Importanti',
      'map': 'Mappa',
      'update': 'Aggiorna',
      'offline': 'Offline',
      'save_offline': 'Salva offline',
      'offline_mode': 'Modalità offline',
      'train_saved_offline': 'Treno salvato per modalità offline',
      'train_saved_manual_offline': 'Treno salvato manualmente (auto-sync offline disattivata)',
      'alerts': 'Avvisi',
      'theme_light': 'Chiaro',
      'theme_dark': 'Scuro',
      'theme_system': 'Sistema',
      'auto': 'Auto',
      'off': 'Spento',
      'managed_by_server': 'Gestito dal server in base al traffico',
      'map_style_dark': 'Scuro',
      'map_style_light': 'Chiaro',
      'map_style_streets': 'Strade',
      'map_style_satellite': 'Satellite',
      'map_style_satellite_streets': 'Sat+Str',
      'other': 'Altro',
      'custom_style_url': 'URL stile personalizzato',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test Notifiche',
      'train_notifications_config': 'Configura notifiche treni',
      'bus_notifications_config': 'Configura notifiche autobus',
      'station_id': 'Station ID',
      'provider': 'Provider',
      'base_url_optional': 'Base URL (opzionale)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Preavviso arrivo stazione',
      'train_arrival_pre_notice_desc': 'Ricevi un avviso N minuti prima dell\'arrivo stimato alla tua fermata (5–20 minuti).',
      'vector_train_logos': 'Loghi Treni Vettoriali',
      'vector_train_logos_desc': 'Scarica e visualizza loghi ufficiali per le categorie dei treni (es. Frecciarossa, Intercity) invece del testo semplice.',
      'update_configuration': 'Aggiorna Configurazione',
      'update_provider_configuration': 'Aggiorna configurazione provider',
      'configuration_update_desc': 'Scarica l\'ultima configurazione dei provider di autobus dal server',
      'configuration_updated_success': 'Configurazione aggiornata con successo',
      'offline_sync_title': 'Sincronizzazione Offline',
      'offline_sync_desc': 'Scarica automaticamente i dati di percorsi e orari quando sincronizzi da una città. I dati verranno salvati localmente e disponibili anche senza connessione.',
      'disclaimer_title': 'BC Transporter Non Sostituisce i Canali Ufficiali',
      'disclaimer_text': 'Questa applicazione non intende in alcun modo sostituire le piattaforme ufficiali delle compagnie ferroviarie o i loro canali di vendita. BC Transporter fornisce informazioni e dati di tracciamento a scopo puramente informativo.\n\nPer l\'acquisto dei biglietti e per verificare disponibilità, tariffe, condizioni di viaggio e conferme ufficiali, è necessario rivolgersi esclusivamente ai canali ufficiali delle compagnie ferroviarie (siti web, app ufficiali, agenzie autorizzate o rivenditori certificati).\n\nI biglietti devono essere acquistati tramite le piattaforme ufficiali; BC Transporter non vende biglietti e non sostituisce i canali ufficiali di vendita.\n\nNon ci assumiamo responsabilità per acquisti effettuati su canali non ufficiali o per informazioni di prezzo/condizioni non aggiornate. Eventuali link a siti di terze parti sono forniti a scopo di comodità e non implicano approvazione o partnership.',
      'language_italian': 'Italiano',
      'language_english': 'English',
      'language_german': 'Deutsch',
      'explore': 'Esplora',
      'greeting': 'Ciao, {name} 👋',
      'ready_to_go': 'Pronto a partire?',
      'refresh_realtime_tooltip': 'Aggiorna dati real-time',
      'train_removed_favorites': 'Treno rimosso dai preferiti',
      'error_removing_favorite': 'Errore durante la rimozione del preferito',
      'undo': 'Annulla',
      'train_added_favorites': 'Treno aggiunto ai preferiti',
      'error_adding_favorite': "Errore durante l'aggiunta",
      'no_route_for_line': 'Nessun percorso disponibile per la linea {line}',
      'upcoming_departures': 'Prossime Partenze',
      'remove_from_favorites': 'Rimuovi dai preferiti',
      'add_to_favorites': 'Aggiungi ai preferiti',
      'guest': 'Ospite',
      'where_to_go_today': 'Dove vuoi andare oggi?',
      'explore_map': 'Esplora la Mappa',
      'explore_map_desc': 'Visualizza bus e treni in tempo reale sulla mappa interattiva.',
      'service_status': 'Stato del Servizio',
      'status_regular': 'Regolare',
      'status_delays': 'Ritardi',
      'your_favorites': 'I tuoi Preferiti',
      'see_all': 'Vedi tutti',
      'no_favorites_saved': 'Nessun preferito salvato',
      'delay_minutes': 'Ritardo: {minutes} min',
      'early_minutes': 'Anticipo: {minutes} min',
      'on_time': 'In orario',
      'remaining_stops': 'Fermate rimanenti: {count}',
      'notify_until': 'Notifica fino a...',
      'choose_stop_from_list': 'Scegli una fermata dalla lista',
      'stops_list_unavailable_general_notification': 'Lista fermate non disponibile, verrà usata notifica generale.',
      'notification_preview': 'Anteprima notifica',
      'notify_to_selected_stop': 'Notifica fino alla fermata selezionata',
      'notify_general': 'Notifica generale',
      'arrivals': 'Arrivi',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Ritardo',
      'origin': 'Origine',
      'destination': 'Destinazione',
      'est_prefix': 'Est: {time}',
      'in_transit': 'In viaggio',
      'on_time_small': 'In orario',
      'loading': 'Caricamento...',
      'delay_short': '+{minutes}min',
      'notifications': 'Notifiche',
      'notifications_disabled': 'Notifiche disattivate',
      'notification_set': 'Notifica impostata',
      'endpoint_check_failed_country': 'Impossibile verificare l\'endpoint dal country selezionata',
      'endpoint_request_failed': 'Richiesta all\'endpoint {candidate} fallita: HTTP {code}',
      'network_error_endpoint_check': 'Errore di rete durante la verifica dell\'endpoint',
      'cannot_determine_url_set_country': 'Non è possibile determinare l\'URL esatto: imposta la country del pannello o utilizza l\'endpoint manuale',
      'disable_notifications_for_this_train': 'Disattiva notifiche per questo treno',
      'retry': 'Riprova',
      'messages': 'Messaggi',
      'close': 'Chiudi',
      'cancelled': 'Annullata',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'BIN',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Accedi per vedere i preferiti',
      'login': 'Accedi',
      'register': 'Registrati',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'Nessuna fermata monitorata',
      'vehicle_info': 'Info Veicolo',
      'vehicle_id': 'ID Veicolo',
      'line': 'Linea',
      'destination_label': 'Destinazione',
      'speed_label': 'Velocità',
      'heading_label': 'Direzione',
      'operator_label': 'Operatore',
      'trip_id_label': 'ID Viaggio',
      'refresh_label': 'Aggiorna',
      'cancel_notification_label': 'Cancella notifica',
      'remove_label': 'Rimuovi',
      'no_monitored_stations': 'Nessuna stazione monitorata',
      'no_monitored_trains': 'Nessun treno monitorato',
      'url_label': 'URL',
      'country_label': 'Country',
      'force_refresh': 'Aggiornamento forzato',
      'notification_cancelled': 'Notifica cancellata',
      'updated_at': 'Aggiornato: {time}',
      'select_item': 'Seleziona {label}',
      'stop_of': 'Fermata di {provider}',
      'saved': 'Salvato',
      'favorite_action': 'Preferito',
      'train_not_found': 'Treno {number} non trovato',
      'train_label': 'Treno {number}',
      'na': 'N/D',
      'unknown': 'Sconosciuta',
      'stop_not_found': 'Fermata "{name}" non trovata',
      'messages_count': 'Messaggi: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Ops! Qualcosa è andato storto',
      'arrival': 'Arrivo',
      'departure': 'Partenza',
      'no_bus_scheduled': 'Nessun bus previsto',
      'scheduled_label': 'Previsto',
      'stats_station_title': 'Statistiche Stazione',
      'stats_day': 'Giorno',
      'stats_week': 'Settim.',
      'stats_month': 'Mese',
      'stats_year': 'Anno',
      'stats_date_of': 'Dati del: {date}',
      'stats_punctuality': 'Puntualità',
      'stats_avg_delay': 'Ritardo Medio',
      'stats_total_trains': 'Treni Totali',
      'stats_cancelled_trains': 'Treni Cancellati',
      'stats_movements_analysis': 'Analisi Movimenti',
      'stats_arrivals': 'Arrivi',
      'stats_departures': 'Partenze',
      'stats_avg_delay_short': 'Ritardo med.',
      'stats_punctuality_short': 'Puntualità',
      'stats_hourly_trend': 'Andamento Orario Ritardi',
      'stats_historical_trend': 'Andamento Storico Ritardi',
      'stats_category_perf': 'Performance per Categoria',
      'stats_worst_trains': 'Treni con Maggior Ritardo',
      'stats_worst_routes': 'Tratte con Maggior Ritardo',
      'stats_no_data': 'Nessun dato disponibile',
      'stats_no_chart_data': 'Nessun dato per il grafico',
      'stats_avg_delay_val': 'Ritardo medio: {val}m',
      'stats_punctuality_val': '{val}% puntualità',
      'stats_unknown_train': 'Treno Sconosciuto',
      'stats_detected_times': 'Rilevato {count} volte',
      'stats_destination': 'Destinazione',
      'stats_analyzed_trips': 'Viaggi analizzati: {count}',
      'activate_monitoring': 'Attiva Monitoraggio',
      'station_not_monitored_msg': 'Questa stazione non è monitorata. Vuoi aggiungerla manualmente al sistema di statistiche?',
      'cancel': 'Annulla',
      'add_now': 'Aggiungi Ora',
      'stats_monitoring_title': 'Monitoraggio Statistiche',
      'stats_monitoring_msg': 'Questa stazione non è ancora inclusa nel sistema di tracciamento. Desideri attivarne il monitoraggio?\n\nNota: L\'elaborazione dei primi dati statistici non sarà immediata e richiederà del tempo per l\'accumulo delle informazioni sui treni.',
      'high': 'Alto',
      'medium': 'Medio',
      'low': 'Basso',
      'critical': 'Critico'
      },
    'en': {
      'trip_stops_title': 'Trip Stops',
      'no_updates': 'No updates',
      'trip_stops_unavailable': 'Stop details not available for {provider}',
      'live': 'LIVE',
      'details_and_position': 'Details & Position',
      'press_for_info': 'Press for info',
      'destination_na': 'Destination N/A',
      'filter_all': 'All',
      'filter_stops': 'Stops',
      'filter_trains': 'Trains',
      'filter_buses': 'Buses',
      'favorites': 'Favorites',
      'automatic': 'Automatic',
      'device_language': 'Device language',
      'settings_header_title': 'Settings',
      'settings_header_subtitle': 'Customize language, theme, and updates in a few taps.',
      'settings_language': 'Language',
      'settings_theme': 'Theme',
      'settings_auto_refresh': 'Auto refresh',
      'settings_configuration': 'Configuration',
      'settings_notifications': 'Notifications',
      'settings_ui': 'UI experience',
      'settings_map': 'Map',
      'settings_map_style': 'Map style',
      'settings_offline_sync': 'Offline sync',
      'settings_disclaimer': 'Info and disclaimer',
      'importantInfo': 'Important Info',
      'map': 'Map',
      'update': 'Update',
      'offline': 'Offline',
      'save_offline': 'Save offline',
      'offline_mode': 'Offline mode',
      'train_saved_offline': 'Train saved for offline mode',
      'train_saved_manual_offline': 'Train saved manually (offline auto-sync disabled)',
      'alerts': 'Alerts',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'auto': 'Auto',
      'off': 'Off',
      'managed_by_server': 'Managed by the server based on traffic',
      'map_style_dark': 'Dark',
      'map_style_light': 'Light',
      'map_style_streets': 'Streets',
      'map_style_satellite': 'Satellite',
      'map_style_satellite_streets': 'Sat+Streets',
      'other': 'Other',
      'custom_style_url': 'Custom style URL',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test Notifications',
      'train_notifications_config': 'Train notifications setup',
      'bus_notifications_config': 'Bus notifications setup',
      'station_id': 'Station ID',
      'provider': 'Provider',
      'base_url_optional': 'Base URL (optional)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Train arrival pre-notice',
      'train_arrival_pre_notice_desc': 'Get an alert N minutes before the estimated arrival at your stop (5–20 minutes).',
      'vector_train_logos': 'Vector train logos',
      'vector_train_logos_desc': 'Download and display official logos for train categories (for example Frecciarossa, Intercity) instead of plain text.',
      'update_configuration': 'Update Configuration',
      'update_provider_configuration': 'Update provider configuration',
      'configuration_update_desc': 'Download the latest bus provider configuration from the server',
      'configuration_updated_success': 'Configuration updated successfully',
      'offline_sync_title': 'Offline Sync',
      'offline_sync_desc': 'Automatically download route and schedule data when you sync from a city. The data will be stored locally and available even without connection.',
      'disclaimer_title': 'BC Transporter Does Not Replace Official Channels',
      'disclaimer_text': 'This application is not intended to replace the official platforms of rail companies or their sales channels. BC Transporter provides tracking information and data for informational purposes only.\n\nFor ticket purchases and to verify availability, fares, travel conditions, and official confirmations, always use the official channels of the rail companies (websites, official apps, authorized agencies, or certified resellers).\n\nTickets must be purchased through official platforms; BC Transporter does not sell tickets and does not replace official sales channels.\n\nWe are not responsible for purchases made through unofficial channels or for outdated price/condition information. Any links to third-party sites are provided for convenience only and do not imply endorsement or partnership.',
      'language_italian': 'Italian',
      'language_english': 'English',
      'language_german': 'German',
      'explore': 'Explore',
      'greeting': 'Hi, {name} 👋',
      'ready_to_go': 'Ready to go?',
      'refresh_realtime_tooltip': 'Refresh real-time data',
      'train_removed_favorites': 'Train removed from favorites',
      'error_removing_favorite': 'Error removing favorite',
      'undo': 'Undo',
      'train_added_favorites': 'Train added to favorites',
      'error_adding_favorite': 'Error adding favorite',
      'no_route_for_line': 'No route available for line {line}',
      'upcoming_departures': 'Upcoming Departures',
      'remove_from_favorites': 'Remove from favorites',
      'add_to_favorites': 'Add to favorites',
      'guest': 'Guest',
      'where_to_go_today': 'Where do you want to go today?',
      'explore_map': 'Explore the Map',
      'explore_map_desc': 'View buses and trains in real time on the interactive map.',
      'service_status': 'Service Status',
      'status_regular': 'Regular',
      'status_delays': 'Delays',
      'your_favorites': 'Your Favorites',
      'see_all': 'View all',
      'no_favorites_saved': 'No saved favorites',
      'delay_minutes': 'Delay: {minutes} min',
      'early_minutes': 'Early: {minutes} min',
      'on_time': 'On time',
      'remaining_stops': 'Remaining stops: {count}',
      'notify_until': 'Notify until...',
      'choose_stop_from_list': 'Choose a stop from the list',
      'stops_list_unavailable_general_notification': 'Stop list unavailable, using general notification.',
      'notification_preview': 'Notification preview',
      'notify_to_selected_stop': 'Notify until selected stop',
      'notify_general': 'General notification',
      'arrivals': 'Arrivals',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Delay',
      'origin': 'Origin',
      'destination': 'Destination',
      'est_prefix': 'Est: {time}',
      'in_transit': 'In transit',
      'on_time_small': 'On time',
      'loading': 'Loading...',
      'delay_short': '+{minutes}min',
      'notifications': 'Notifications',
      'notifications_disabled': 'Notifications disabled',
      'notification_set': 'Notification set',
      'endpoint_check_failed_country': 'Unable to verify endpoint from selected country',
      'endpoint_request_failed': 'Request to endpoint {candidate} failed: HTTP {code}',
      'network_error_endpoint_check': 'Network error while checking endpoint',
      'cannot_determine_url_set_country': 'Cannot determine exact URL: set the panel country or use manual endpoint',
      'disable_notifications_for_this_train': 'Disable notifications for this train',
      'retry': 'Retry',
      'messages': 'Messages',
      'close': 'Close',
      'cancelled': 'Cancelled',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'PLT',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Login to see favorites',
      'login': 'Login',
      'register': 'Register',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'No monitored stops',
      'vehicle_info': 'Vehicle Info',
      'vehicle_id': 'Vehicle ID',
      'line': 'Line',
      'destination_label': 'Destination',
      'speed_label': 'Speed',
      'heading_label': 'Heading',
      'operator_label': 'Operator',
      'trip_id_label': 'Trip ID',
      'refresh_label': 'Refresh',
      'cancel_notification_label': 'Cancel notification',
      'remove_label': 'Remove',
      'no_monitored_stations': 'No monitored stations',
      'no_monitored_trains': 'No monitored trains',
      'url_label': 'URL',
      'country_label': 'Country',
      'force_refresh': 'Force refresh',
      'notification_cancelled': 'Notification cancelled',
      'updated_at': 'Updated: {time}',
      'select_item': 'Select {label}',
      'stop_of': 'Stop of {provider}',
      'saved': 'Saved',
      'favorite_action': 'Favorite',
      'train_not_found': 'Train {number} not found',
      'train_label': 'Train {number}',
      'na': 'N/A',
      'unknown': 'Unknown',
      'stop_not_found': 'Stop "{name}" not found',
      'messages_count': 'Messages: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Oops! Something went wrong',
      'arrival': 'Arrival',
      'departure': 'Departure',
      'no_bus_scheduled': 'No buses scheduled',
      'scheduled_label': 'Scheduled',
      'stats_station_title': 'Station Statistics',
      'stats_day': 'Day',
      'stats_week': 'Week',
      'stats_month': 'Month',
      'stats_year': 'Year',
      'stats_date_of': 'Data: {date}',
      'stats_punctuality': 'Punctuality',
      'stats_avg_delay': 'Average Delay',
      'stats_total_trains': 'Total Trains',
      'stats_cancelled_trains': 'Cancelled Trains',
      'stats_movements_analysis': 'Movements Analysis',
      'stats_arrivals': 'Arrivals',
      'stats_departures': 'Departures',
      'stats_avg_delay_short': 'Avg Delay',
      'stats_punctuality_short': 'Punctuality',
      'stats_hourly_trend': 'Hourly Delay Trend',
      'stats_historical_trend': 'Historical Delay Trend',
      'stats_category_perf': 'Performance by Category',
      'stats_worst_trains': 'Worst Performing Trains',
      'stats_worst_routes': 'Worst Performing Routes',
      'stats_no_data': 'No data available',
      'stats_no_chart_data': 'No data for chart',
      'stats_avg_delay_val': 'Avg Delay: {val}m',
      'stats_punctuality_val': '{val}% punctuality',
      'stats_unknown_train': 'Unknown Train',
      'stats_detected_times': 'Detected {count} times',
      'stats_destination': 'Destination',
      'stats_analyzed_trips': 'Analyzed trips: {count}',
      'activate_monitoring': 'Activate Monitoring',
      'station_not_monitored_msg': 'This station is not monitored. Do you want to add it manually to the statistics system?',
      'cancel': 'Cancel',
      'add_now': 'Add Now',
      'stats_monitoring_title': 'Statistics Monitoring',
      'stats_monitoring_msg': 'This station is not yet included in the tracking system. Do you want to activate monitoring for it?\n\nNote: The processing of the first statistical data will not be immediate and will require time to accumulate train information.',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'critical': 'Critical',
    },
    'de': {
      'trip_stops_title': 'Haltestellen der Fahrt',
      'no_updates': 'Keine Aktualisierungen',
      'trip_stops_unavailable': 'Haltestellendetails nicht verfügbar für {provider}',
      'live': 'LIVE',
      'details_and_position': 'Details & Position',
      'press_for_info': 'Zum Anzeigen tippen',
      'destination_na': 'Ziel N/V',
      'filter_all': 'Alle',
      'filter_stops': 'Haltestellen',
      'filter_trains': 'Züge',
      'filter_buses': 'Busse',
      'favorites': 'Favoriten',
      'automatic': 'Automatisch',
      'device_language': 'Gerätesprache',
      'settings_header_title': 'Einstellungen',
      'settings_header_subtitle': 'Sprache, Design und Aktualisierungen mit wenigen Tipps anpassen.',
      'settings_language': 'Sprache',
      'settings_theme': 'Design',
      'settings_auto_refresh': 'Automatische Aktualisierung',
      'settings_configuration': 'Konfiguration',
      'settings_notifications': 'Benachrichtigungen',
      'settings_ui': 'UI-Erlebnis',
      'settings_map': 'Karte',
      'settings_map_style': 'Kartenstil',
      'settings_offline_sync': 'Offline-Synchronisierung',
      'settings_disclaimer': 'Informationen und Hinweis',
      'importantInfo': 'Wichtige Informationen',
      'map': 'Karte',
      'update': 'Aktualisieren',
      'offline': 'Offline',
      'save_offline': 'Offline speichern',
      'offline_mode': 'Offline-Modus',
      'train_saved_offline': 'Zug für den Offline-Modus gespeichert',
      'train_saved_manual_offline': 'Zug manuell gespeichert (Offline-Autosync deaktiviert)',
      'alerts': 'Hinweise',
      'theme_light': 'Hell',
      'theme_dark': 'Dunkel',
      'theme_system': 'System',
      'auto': 'Auto',
      'off': 'Aus',
      'managed_by_server': 'Vom Server basierend auf dem Verkehr verwaltet',
      'map_style_dark': 'Dunkel',
      'map_style_light': 'Hell',
      'map_style_streets': 'Straßen',
      'map_style_satellite': 'Satellit',
      'map_style_satellite_streets': 'Sat+Straßen',
      'other': 'Andere',
      'custom_style_url': 'Benutzerdefinierte Stil-URL',
      'custom_style_hint': 'mapbox://styles/…',
      'test_notifications': 'Test-Benachrichtigungen',
      'train_notifications_config': 'Zug-Benachrichtigungen konfigurieren',
      'bus_notifications_config': 'Bus-Benachrichtigungen konfigurieren',
      'station_id': 'Station-ID',
      'provider': 'Anbieter',
      'base_url_optional': 'Basis-URL (optional)',
      'trainboard_prod': 'Trainboard (prod)',
      'direct_rfi': 'Direct (RFI)',
      'train_arrival_pre_notice': 'Vorabhinweis Zugankunft',
      'train_arrival_pre_notice_desc': 'Erhalte eine Benachrichtigung N Minuten vor der geschätzten Ankunft an deiner Haltestelle (5–20 Minuten).',
      'vector_train_logos': 'Vektor-Zuglogos',
      'vector_train_logos_desc': 'Offizielle Logos für Zugkategorien herunterladen und anzeigen (z. B. Frecciarossa, Intercity) statt nur Text.',
      'update_configuration': 'Konfiguration aktualisieren',
      'update_provider_configuration': 'Anbieter-Konfiguration aktualisieren',
      'configuration_update_desc': 'Die neueste Bus-Anbieterkonfiguration vom Server herunterladen',
      'configuration_updated_success': 'Konfiguration erfolgreich aktualisiert',
      'offline_sync_title': 'Offline-Synchronisierung',
      'offline_sync_desc': 'Routen- und Fahrplandaten automatisch herunterladen, wenn du von einer Stadt synchronisierst. Die Daten werden lokal gespeichert und sind auch ohne Verbindung verfügbar.',
      'disclaimer_title': 'BC Transporter Ersetzt Nicht die Offiziellen Kanäle',
      'disclaimer_text': 'Diese Anwendung ist nicht dazu bestimmt, die offiziellen Plattformen der Bahnunternehmen oder deren Verkaufskanäle zu ersetzen. BC Transporter stellt Tracking-Informationen und Daten ausschließlich zu Informationszwecken bereit.\n\nFür Ticketkäufe und zur Überprüfung von Verfügbarkeit, Preisen, Reisebedingungen und offiziellen Bestätigungen nutze bitte immer die offiziellen Kanäle der Bahnunternehmen (Websites, offizielle Apps, autorisierte Agenturen oder zertifizierte Wiederverkäufer).\n\nTickets müssen über die offiziellen Plattformen gekauft werden; BC Transporter verkauft keine Tickets und ersetzt nicht die offiziellen Verkaufskanäle.\n\nWir übernehmen keine Verantwortung für Käufe über inoffizielle Kanäle oder für veraltete Preis-/Bedingungsinformationen. Links zu Drittanbietern dienen nur der Bequemlichkeit und bedeuten keine Empfehlung oder Partnerschaft.',
      'language_italian': 'Italienisch',
      'language_english': 'Englisch',
      'language_german': 'Deutsch',
      'explore': 'Entdecken',
      'greeting': 'Hallo, {name} 👋',
      'ready_to_go': 'Bereit loszufahren?',
      'refresh_realtime_tooltip': 'Echtzeitdaten aktualisieren',
      'train_removed_favorites': 'Zug aus Favoriten entfernt',
      'error_removing_favorite': 'Fehler beim Entfernen des Favoriten',
      'undo': 'Rückgängig',
      'train_added_favorites': 'Zug zu Favoriten hinzugefügt',
      'error_adding_favorite': 'Fehler beim Hinzufügen',
      'no_route_for_line': 'Keine Route verfügbar für Linie {line}',
      'upcoming_departures': 'Nächste Abfahrten',
      'remove_from_favorites': 'Aus Favoriten entfernen',
      'add_to_favorites': 'Zu Favoriten hinzufügen',
      'guest': 'Gast',
      'where_to_go_today': 'Wohin möchtest du heute fahren?',
      'explore_map': 'Karte erkunden',
      'explore_map_desc': 'Zeigt Busse und Züge in Echtzeit auf der interaktiven Karte an.',
      'service_status': 'Betriebsstatus',
      'status_regular': 'Regulär',
      'status_delays': 'Verspätungen',
      'your_favorites': 'Deine Favoriten',
      'see_all': 'Alle ansehen',
      'no_favorites_saved': 'Keine Favoriten gespeichert',
      'delay_minutes': 'Verspätung: {minutes} min',
      'early_minutes': 'Früh: {minutes} min',
      'on_time': 'Pünktlich',
      'remaining_stops': 'Verbleibende Haltestellen: {count}',
      'notify_until': 'Benachrichtigen bis...',
      'choose_stop_from_list': 'Wähle eine Haltestelle aus der Liste',
      'stops_list_unavailable_general_notification': 'Haltestellenliste nicht verfügbar, allgemeine Benachrichtigung wird verwendet.',
      'notification_preview': 'Benachrichtigungs-Vorschau',
      'notify_to_selected_stop': 'Benachrichtigen bis zur ausgewählten Haltestelle',
      'notify_general': 'Allgemeine Benachrichtigung',
      'arrivals': 'Ankünfte',
      'global_label': 'Global',
      'beta': 'BETA',
      'delay_label': 'Verspätung',
      'origin': 'Abfahrt',
      'destination': 'Ziel',
      'est_prefix': 'Est: {time}',
      'in_transit': 'Unterwegs',
      'on_time_small': 'Pünktlich',
      'loading': 'Lädt...',
      'delay_short': '+{minutes}min',
      'notifications': 'Benachrichtigungen',
      'notifications_disabled': 'Benachrichtigungen deaktiviert',
      'notification_set': 'Benachrichtigung gesetzt',
      'endpoint_check_failed_country': 'Endpunkt konnte aus dem ausgewählten Land nicht überprüft werden',
      'endpoint_request_failed': 'Anforderung an Endpunkt {candidate} fehlgeschlagen: HTTP {code}',
      'network_error_endpoint_check': 'Netzwerkfehler beim Überprüfen des Endpunkts',
      'cannot_determine_url_set_country': 'URL kann nicht bestimmt werden: Setze das Land im Panel oder verwende den manuellen Endpunkt',
      'disable_notifications_for_this_train': 'Benachrichtigungen für diesen Zug deaktivieren',
      'retry': 'Erneut versuchen',
      'messages': 'Nachrichten',
      'close': 'Schließen',
      'cancelled': 'Abgesagt',
      'minutes_short': '{minutes} min',
      'platform_abbr': 'BIN',
      'seconds_60': '60s',
      'login_to_see_favorites': 'Anmelden, um Favoriten zu sehen',
      'login': 'Anmelden',
      'register': 'Registrieren',
      'id_prefix': 'ID: {id}',
      'no_monitored_stops': 'Keine überwachten Haltestellen',
      'vehicle_info': 'Fahrzeuginfo',
      'vehicle_id': 'Fahrzeug-ID',
      'line': 'Linie',
      'destination_label': 'Ziel',
      'speed_label': 'Geschwindigkeit',
      'heading_label': 'Richtung',
      'stats_station_title': 'Stationsstatistiken',
      'stats_day': 'Tag',
      'stats_week': 'Woche',
      'stats_month': 'Monat',
      'stats_year': 'Jahr',
      'stats_date_of': 'Datum: {date}',
      'stats_punctuality': 'Pünktlichkeit',
      'stats_avg_delay': 'Durchschnittliche Verspätung',
      'stats_total_trains': 'Gesamtzüge',
      'stats_cancelled_trains': 'Ausgefallene Züge',
      'stats_movements_analysis': 'Bewegungsanalyse',
      'stats_arrivals': 'Ankünfte',
      'stats_departures': 'Abfahrten',
      'stats_avg_delay_short': 'Durchschn. Versp.',
      'stats_punctuality_short': 'Pünktlichkeit',
      'stats_hourly_trend': 'Stündlicher Verspätungstrend',
      'stats_historical_trend': 'Historischer Verspätungstrend',
      'stats_category_perf': 'Leistung nach Kategorie',
      'stats_worst_trains': 'Züge mit den größten Verspätungen',
      'stats_worst_routes': 'Strecken mit den größten Verspätungen',
      'stats_no_data': 'Keine Daten verfügbar',
      'stats_no_chart_data': 'Keine Daten für das Diagramm',
      'stats_avg_delay_val': 'Durchschn. Versp.: {val}m',
      'stats_punctuality_val': '{val}% Pünktlichkeit',
      'stats_unknown_train': 'Unbekannter Zug',
      'stats_detected_times': 'Erkannt {count} Mal',
      'stats_destination': 'Ziel',
      'stats_analyzed_trips': 'Analysierte Fahrten: {count}',
      'operator_label': 'Betreiber',
      'trip_id_label': 'Fahrt-ID',
      'refresh_label': 'Aktualisieren',
      'cancel_notification_label': 'Benachrichtigung löschen',
      'remove_label': 'Entfernen',
      'no_monitored_stations': 'Keine überwachten Stationen',
      'no_monitored_trains': 'Keine überwachten Züge',
      'url_label': 'URL',
      'country_label': 'Land',
      'force_refresh': 'Erzwungene Aktualisierung',
      'notification_cancelled': 'Benachrichtigung gelöscht',
      'updated_at': 'Aktualisiert: {time}',
      'select_item': 'Wähle {label}',
      'stop_of': 'Haltestelle von {provider}',
      'saved': 'Gespeichert',
      'favorite_action': 'Favorit',
      'train_not_found': 'Zug {number} nicht gefunden',
      'train_label': 'Zug {number}',
      'na': 'N/V',
      'unknown': 'Unbekannt',
      'stop_not_found': 'Haltestelle "{name}" nicht gefunden',
      'messages_count': 'Nachrichten: {count}',
      'category_number': '{category} {number}',
      'something_went_wrong': 'Hoppla! Etwas ist schief gelaufen',
      'arrival': 'Ankunft',
      'departure': 'Abfahrt',
      'no_bus_scheduled': 'Keine Busse geplant',
      'scheduled_label': 'Geplant',
      'activate_monitoring': 'Überwachung aktivieren',
      'station_not_monitored_msg': 'Dieser Bahnhof wird nicht überwacht. Möchten Sie ihn manuell zum Statistiksystem hinzufügen?',
      'cancel': 'Abbrechen',
      'add_now': 'Jetzt hinzufügen',
      'stats_monitoring_title': 'Statistik-Überwachung',
      'stats_monitoring_msg': 'Dieser Bahnhof ist noch nicht im Tracking-System enthalten. Möchten Sie die Überwachung dafür aktivieren?\n\nHinweis: Die Verarbeitung der ersten statistischen Daten erfolgt nicht sofort und erfordert Zeit, um Zuginformationen zu sammeln.',
      'high': 'Hoch',
      'medium': 'Mittel',
      'low': 'Niedrig',
      'critical': 'Kritisch'
    }
  };

  static String t(BuildContext context, String key, {Map<String, String>? params, String? fallback}) {
    final settings = Provider.of<SettingsProvider>(context, listen: false);
    final code = settings.appLocale?.languageCode ?? Localizations.localeOf(context).languageCode;
    final map = _t[code] ?? _t['it']!;
    var res = map[key] ?? fallback ?? key;
    if (params != null && params.isNotEmpty) {
      params.forEach((k, v) {
        res = res.replaceAll('{$k}', v);
      });
    }
    return res;
  }
}